# Generated by go2rpm 1.10.0
%bcond_without check

# https://github.com/geraldosimiao/alertas.git
%global goipath         github.com/geraldosimiao/alertas
%global tag             0.0.2

# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
# ---
# New Fedora packages should use %%gometa -f, which makes the package
# ExclusiveArch to %%golang_arches_future and thus excludes the package from
# %%ix86. If the new package is needed as a dependency for another package,
# please consider removing that package from %%ix86 in the same way, instead of
# building more go packages for i686. If your package is not a leaf package,
# you'll need to coordinate the removal of the package's dependents first.
# ---
# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
%gometa -L -f


%global common_description %{expand:
Alertas is a program written in Go that gathers and filters weather warnings from INMET-Instuto Nacional de Meteorologia https://alertas2.inmet.gov.br/}

%global golicenses      LICENSE
%global godocs          README.md DOC.md

Name:           alertas
Version:        0.1
Release:        1%{?dist}
Summary:        Go software to fetch data from INMET, the Brazilian Nacional Meteorologic Institute

License:        GPL-3.0-only
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%build
%gobuild -o %{gobuilddir}/bin/alertas %{goipath}

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc README.md DOC.md
%{_bindir}/*

%gopkgfiles

%changelog
* Thu Jan 25 2024 Geraldo Simião <geraldosimiao@fedoraproject.org> - 0.1
- Initial build
